defmodule Digestif.PBKDF2Test do
  use ExUnit.Case, async: true

  alias Digestif.PBKDF2

  @password "correct horse battery staple"

  # Generated by pbkdf2_elixir 2.3.1 through
  # Pbkdf2.Base.hash_password/3 with Digestif's documented parameters and
  # deterministic salts. These literals survive removal of that dependency
  # and pin the storage compatibility it used to own.
  @pbkdf2_elixir_fixtures [
    {
      "correct horse battery staple",
      "$pbkdf2-sha256$600000$MDEyMzQ1Njc4OWFiY2RlZg$" <>
        "bEpkaq0Q0Get1ft52QeKFtqD1Q.BZwqOdZOySebZSTY"
    },
    {
      "pässwörd/密碼",
      "$pbkdf2-sha256$600000$AAECAwQFBgcICQoLDA0ODw$" <>
        "bvjcLOYbLwqigkZGOUTWYS093dR0Vz9ItGDg24yeZo8"
    },
    {
      "a password with a NUL: \0 and punctuation !@#",
      "$pbkdf2-sha256$600000$.BEiM0RVZneImaq7zN3u/w$" <>
        "ySjIsdfePSmiT37PGt3TzRGWn9p/CecPENzkJ35Qe7Y"
    }
  ]

  test "mints a passlib-style hash that round-trips and fails the wrong password" do
    assert PBKDF2.algorithm() == "pbkdf2-sha256"
    assert {:ok, encoded} = PBKDF2.hash(@password, [])

    assert ["", "pbkdf2-sha256", "600000", salt, digest] =
             String.split(encoded, "$")

    refute String.contains?(salt, ["+", "="])
    refute String.contains?(digest, ["+", "="])
    assert PBKDF2.verify(@password, encoded, [])
    refute PBKDF2.verify("wrong password", encoded, [])
    refute PBKDF2.needs_rehash?(encoded, [])
    assert PBKDF2.needs_rehash?(encoded, iterations: 700_000)
  end

  test "verifies hashes minted by pbkdf2_elixir with the documented parameters" do
    for {password, encoded} <- @pbkdf2_elixir_fixtures do
      assert PBKDF2.verify(password, encoded, [])
      refute PBKDF2.verify(password <> "wrong", encoded, [])
      refute PBKDF2.needs_rehash?(encoded, [])
    end
  end

  test "rejects non-canonical trailing bits in salt and digest segments" do
    assert {:ok, encoded} = PBKDF2.hash(@password, [])
    ["", algorithm, rounds, salt, digest] = String.split(encoded, "$")

    flip_unused_bit = fn segment ->
      {prefix, <<last_character>>} = String.split_at(segment, -1)
      prefix <> <<last_character + 1>>
    end

    decode = fn segment ->
      segment
      |> String.replace(".", "+")
      |> Base.decode64!(padding: false)
    end

    non_canonical_salt = flip_unused_bit.(salt)
    assert decode.(non_canonical_salt) == decode.(salt)

    refute PBKDF2.verify(
             @password,
             Enum.join(["", algorithm, rounds, non_canonical_salt, digest], "$"),
             []
           )

    non_canonical_digest = flip_unused_bit.(digest)
    assert decode.(non_canonical_digest) == decode.(digest)

    refute PBKDF2.verify(
             @password,
             Enum.join(["", algorithm, rounds, salt, non_canonical_digest], "$"),
             []
           )
  end

  test "rejects a leading-zero round count" do
    assert {:ok, encoded} = PBKDF2.hash(@password, [])
    non_canonical = String.replace(encoded, "$600000$", "$0600000$")

    refute PBKDF2.verify(@password, non_canonical, [])
    assert PBKDF2.needs_rehash?(non_canonical, [])
  end

  test "accepts a one-byte salt but rejects an empty salt even when the digest matches" do
    encode = fn binary ->
      binary
      |> Base.encode64(padding: false)
      |> String.replace("+", ".")
    end

    one_byte_salt = <<0>>
    one_byte_digest = :crypto.pbkdf2_hmac(:sha256, @password, one_byte_salt, 600_000, 32)

    assert PBKDF2.verify(
             @password,
             "$pbkdf2-sha256$600000$#{encode.(one_byte_salt)}$#{encode.(one_byte_digest)}",
             []
           )

    empty_salt_digest = :crypto.pbkdf2_hmac(:sha256, @password, "", 600_000, 32)

    refute PBKDF2.verify(
             @password,
             "$pbkdf2-sha256$600000$$#{encode.(empty_salt_digest)}",
             []
           )
  end

  test "missing-user and malformed-hash paths fail closed through dummy work" do
    for operation <- [
          fn -> PBKDF2.no_user_verify(@password, []) end,
          fn -> PBKDF2.verify(@password, "not a hash", []) end,
          fn -> PBKDF2.verify(@password, "$pbkdf2-sha256$600000$!!!$!!!", []) end
        ] do
      refute operation.()
    end
  end

  test "stored values outside the preflight budget fail closed" do
    salt = "Igmnl/E3JR2Cevlp0Cshdw"

    for rejected <- [
          # Rounds one step over the default budget (the configured cost).
          "$pbkdf2-sha256$600001$#{salt}$digest",
          # OTP rejects zero rounds; Digestif keeps that on the dummy path.
          "$pbkdf2-sha256$0$#{salt}$digest",
          # This adapter never accepts another digest identifier.
          "$pbkdf2-sha512$600000$#{salt}$digest",
          "",
          "not a hash"
        ] do
      refute PBKDF2.verify(@password, rejected, [])
      assert PBKDF2.needs_rehash?(rejected, [])
    end

    prefix = "$pbkdf2-sha256$600000$"
    at_ceiling = prefix <> String.duplicate("A", 160 - byte_size(prefix))
    over_ceiling = at_ceiling <> "A"

    assert byte_size(at_ceiling) == 160
    refute PBKDF2.verify(@password, at_ceiling, [])
    refute PBKDF2.needs_rehash?(at_ceiling, [])

    assert byte_size(over_ceiling) == 161
    refute PBKDF2.verify(@password, over_ceiling, [])
    assert PBKDF2.needs_rehash?(over_ceiling, [])
  end

  test "a raised verification budget admits stronger stored hashes" do
    {:ok, strong} = PBKDF2.hash(@password, iterations: 700_000)

    # Over the default budget: fails closed through 600,000 rounds of dummy
    # work rather than trusting the stored cost.
    refute PBKDF2.verify(@password, strong, [])

    assert PBKDF2.verify(@password, strong, max_iterations: 700_000)
    assert PBKDF2.needs_rehash?(strong, max_iterations: 700_000)

    refute PBKDF2.needs_rehash?(
             strong,
             iterations: 700_000,
             max_iterations: 700_000
           )
  end

  test "malformed in-budget values fail closed after full format parsing" do
    valid_digest = String.duplicate("A", 43)

    for malformed <- [
          "$pbkdf2-sha256$600000$!!!$!!!",
          "$pbkdf2-sha256$600000$missing-digest",
          "$pbkdf2-sha256$600000$a$b$c$d",
          "$pbkdf2-sha256$600000$+A$#{valid_digest}",
          "$pbkdf2-sha256$600000$AA==$#{valid_digest}",
          "$pbkdf2-sha256$600000$AA-$#{valid_digest}",
          "$pbkdf2-sha256$600000$AA$#{String.duplicate("A", 42)}_",
          "$pbkdf2-sha256$600000$AA$AA",
          # A zero-length digest must never turn comparison into a vacuous
          # success for every password.
          "$pbkdf2-sha256$600000$c2FsdA$"
        ] do
      refute PBKDF2.verify(@password, malformed, [])
    end
  end

  test "configuration options are validated at configuration time" do
    assert :ok = PBKDF2.validate_options!([])
    assert :ok = PBKDF2.validate_options!(iterations: 600_000)
    assert :ok = PBKDF2.validate_options!(iterations: 600_000, max_iterations: 10_000_000)

    # OWASP floor for new HMAC-SHA-256 hashes and the absolute ceiling.
    assert_raise ArgumentError, ~r/iterations/, fn ->
      PBKDF2.validate_options!(iterations: 599_999)
    end

    assert_raise ArgumentError, ~r/iterations/, fn ->
      PBKDF2.validate_options!(iterations: 10_000_001)
    end

    # A budget below the configured cost would mint hashes its own
    # verification bound rejects.
    assert_raise ArgumentError, ~r/max_iterations/, fn ->
      PBKDF2.validate_options!(iterations: 700_000, max_iterations: 600_000)
    end

    # Backend vocabulary and injection are no longer parallel ways to
    # configure the one OTP implementation.
    assert_raise ArgumentError, fn ->
      PBKDF2.validate_options!(rounds: 600_000)
    end

    assert_raise ArgumentError, fn ->
      PBKDF2.validate_options!(backend: Digestif.NoSuchPbkdf2Backend)
    end
  end
end
